dist: bionic
language: c
os:
  - linux
compiler:
  - gcc
install:
  - sudo apt-get install --yes cppcheck
  - sudo apt-get install --yes cmake
  - sudo apt-get install --yes libgtest-dev
  - sudo apt-get install --yes gcovr
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -
script:
  - cppcheck --quiet --error-exitcode=1 main.c library.c main_test.cpp
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov -f  <(gcovr -e '.*/.*' -x)
