dist: bionic
language: c
os:
  - linux
compiler:
  - gcc
install:
  - sudo apt-get install cmake
  - sudo apt-get install libgtest-dev
  - sudo apt-get install -qq cppcheck
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -
script:
  - cmake CMakeLists.txt
  - make
  - ls
  - cppcheck --quiet --error-exitcode=1
after_success:
  - bash <(curl -s https://codecov.io/bash)
