dist: bionic
language: c
os:
  - linux
compiler:
  - gcc
install:
 - sudo apt install clang-format
 - sudo apt install clang-tidy
 - sudo apt install cppcheck
 - sudo pip install codecov
 - sudo apt install cmake
 - sudo apt install libgtest-dev
 - cd /usr/src/gtest
 - sudo cmake CMakeLists.txt
 - sudo make
 - sudo cp *.a /usr/lib
 - cd -
script:
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - ls
  - cppcheck --quiet --error-exitcode=1 main.c library.c main_test.cpp
