dist: bionic
language: c
os:
  - linux
compiler:
  - gcc
install:
  - sudo apt install cmake
  - sudo apt install libgtest-dev
  - sudo apt install -qq cppcheck
  - sudo apt install clang-format
  - sudo apt install clang-tidy
  - sudo apt install cppcheck
  - sudo apt install valgrind
  - cp *.a /usr/lib
  - cd -
script:
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - cppcheck --quiet --error-exitcode=1 main.c library.c main_test.cpp
