dist: bionic
language: c
os:
  - linux
compiler:
  - gcc
install:
  - apt install cmake
  - apt install libgtest-dev
  - apt install -qq cppcheck
  - apt install clang-format
  - apt install clang-tidy
  - apt install cppcheck
  - apt install valgrind
  - make
  - cp *.a /usr/lib
  - cd -
script:
  - cd /usr/src/gtest
  - cmake CMakeLists.txt
  - make
  - cppcheck --quiet --error-exitcode=1 main.c library.c main_test.cpp
